const UTILIZADORES=[{id:"admin",nome:"Responsável de Estatística",cargo:"Administrador",codigo:"CMB2026",perfil:"admin",cor:"#1F3864",icone:"🔐"},{id:"editor",nome:"Editor da Comissão",cargo:"Editor",codigo:"EDITOR26",perfil:"editor",cor:"#1B5E20",icone:"✏️"},{id:"leitor",nome:"Consulta e Relatórios",cargo:"Leitor",codigo:"LEITOR26",perfil:"leitor",cor:"#7B3F00",icone:"👁"}];
const PODE={admin:{registar:true,editar:true,eliminar:true,gerir:true},editor:{registar:true,editar:true,eliminar:false,gerir:false},leitor:{registar:false,editar:false,eliminar:false,gerir:false}};
const CLASSES=["Nazaré de Castro","Castro João dos Santos","Revº Diogo de Sousa"];
const ORGANISMOS=["Organização dos Homens","Organização das Mulheres","OJA","Juventude","Ministério com Crianças","Nenhum"];
const STATUS=["Catecúmeno","À Prova","Efectivo","Falecido","Transferido"];
const SEXO=["Masculino","Feminino"];
const GUIAS={"Nazaré de Castro":"Marolina Bule Domingos","Castro João dos Santos":"Eva Francisco Ernesto","Revº Diogo de Sousa":"Florinda André João"};
const DIRECTORES={"Organização dos Homens":"Mateus Zombo","Organização das Mulheres":"Teresa Manuel João","OJA":"Dionísia N. Samuel","Juventude":"Por nomear","Ministério com Crianças":"Rodrigues Luís Dembo"};
const COR={azul:"#1F3864",azulM:"#2E5096",dourado:"#7B3F00",verde:"#1B5E20",verm:"#B71C1C",cinza:"#37474F",cinzaL:"#ECEFF1"};
const CHAVE="cm_benjamim_v1";
const DADOS=[{id:1,nome:"Marolina Bule Domingos",classe:"Nazaré de Castro",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2018-03-10",telefone:"",obs:"Guia de Classe"},{id:2,nome:"Adão Lopes Mainga",classe:"Nazaré de Castro",sexo:"Masculino",status:"Efectivo",organismo:"Organização dos Homens",baptizado:true,dataBaptismo:"2015-06-14",telefone:"",obs:"Vice Guia Leigo"},{id:3,nome:"Teresa Manuel João",classe:"Nazaré de Castro",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2012-11-20",telefone:"",obs:"Directora Org. Mulheres"},{id:4,nome:"Beatriz Gaspar Cavunga",classe:"Nazaré de Castro",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2010-06-05",telefone:"",obs:"Guia Leiga"},{id:5,nome:"Eva Francisco Ernesto",classe:"Castro João dos Santos",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2014-03-15",telefone:"",obs:"Guia de Classe"},{id:6,nome:"Adão António Ernesto",classe:"Castro João dos Santos",sexo:"Masculino",status:"Efectivo",organismo:"Organização dos Homens",baptizado:true,dataBaptismo:"2011-11-27",telefone:"",obs:"Presidente da Junta"},{id:7,nome:"Florinda André João",classe:"Revº Diogo de Sousa",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2009-06-14",telefone:"",obs:"Guia de Classe"},{id:8,nome:"Marquinha Miguel",classe:"Revº Diogo de Sousa",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2015-03-22",telefone:"",obs:"Evangelismo e Oração"}];
function lerLocal(){try{const r=localStorage.getItem(CHAVE);if(r)return JSON.parse(r);}catch(_){}return null;}
function guardarLocal(m){try{localStorage.setItem(CHAVE,JSON.stringify({membros:m,ts:Date.now()}));}catch(_){}}
function useStorage(){const[membros,setMembros]=React.useState(()=>{const l=lerLocal();return l?l.membros:DADOS;});const[salvando,setSalvando]=React.useState(false);const[guardadoOk,setGuardadoOk]=React.useState(false);const guardar=React.useCallback(async(novos)=>{setSalvando(true);setMembros(novos);guardarLocal(novos);try{if(typeof window.storage!=="undefined"){await window.storage.set(CHAVE,JSON.stringify({membros:novos,ts:Date.now()}),true);}}catch(_){}setSalvando(false);setGuardadoOk(true);setTimeout(()=>setGuardadoOk(false),2000);},[]);return{membros,salvando,guardadoOk,guardar};}
function LogoIMU({size=48}){return React.createElement("svg",{viewBox:"0 0 200 230",width:size,height:size,xmlns:"http://www.w3.org/2000/svg"},React.createElement("path",{d:"M68 222 C54 194 22 176 20 144 C18 116 38 104 44 82 C49 63 40 46 47 30 C54 14 70 7 79 0 C72 20 76 36 84 50 C90 62 88 73 83 87 C77 105 65 116 67 138 C69 156 83 167 88 185 C93 198 91 212 87 224 Z",fill:"#D32F2F"}),React.createElement("path",{d:"M68 222 C54 194 22 176 20 144 C18 116 38 104 44 82 C49 63 40 46 47 30 C60 44 65 60 60 78 C55 96 42 108 46 130 C49 150 64 161 68 180 C72 195 70 208 68 222 Z",fill:"white",opacity:"0.3"}),React.createElement("rect",{x:"102",y:"12",width:"20",height:"206",rx:"3",fill:"#111"}),React.createElement("rect",{x:"70",y:"70",width:"116",height:"20",rx:"3",fill:"#111"}));}
function Badge({txt}){const m={Efectivo:{bg:"#E8F5E9",c:"#1B5E20"},"Catecúmeno":{bg:"#E3F2FD",c:"#0D47A1"},"À Prova":{bg:"#FFF3E0",c:"#E65100"},Falecido:{bg:"#EFEBE9",c:"#4E342E"},Transferido:{bg:"#F3E5F5",c:"#6A1B9A"}};const s=m[txt]||{bg:"#ECEFF1",c:"#555"};return React.createElement("span",{style:{background:s.bg,color:s.c,border:`1px solid ${s.c}30`,borderRadius:12,padding:"2px 10px",fontSize:11,fontWeight:700,whiteSpace:"nowrap"}},txt);}
function MiniBar({valor,max,color}){return React.createElement("div",{style:{height:5,borderRadius:3,background:"#eee",overflow:"hidden",flex:1}},React.createElement("div",{style:{width:`${Math.round((valor/Math.max(max,1))*100)}%`,height:"100%",background:color,borderRadius:3}}));}
function StatCard({icon,label,value,sub,color}){return React.createElement("div",{style:{background:"#fff",borderLeft:`4px solid ${color}`,border:`1px solid ${color}18`,borderRadius:10,padding:"13px 16px",flex:"1 1 100px"}},React.createElement("div",{style:{fontSize:18,marginBottom:2}},icon),React.createElement("div",{style:{fontSize:23,fontWeight:900,color,fontFamily:"Georgia,serif",lineHeight:1}},value),React.createElement("div",{style:{fontSize:10,fontWeight:700,color:"#666",marginTop:3,textTransform:"uppercase"}},label),sub&&React.createElement("div",{style:{fontSize:9,color:"#aaa",marginTop:1}},sub));}