const UTILIZADORES=[{id:"admin",nome:"Responsável de Estatística",cargo:"Administrador",codigo:"CMB2026",perfil:"admin",cor:"#1F3864",icone:"🔐"},{id:"editor",nome:"Editor da Comissão",cargo:"Editor",codigo:"EDITOR26",perfil:"editor",cor:"#1B5E20",icone:"✏️"},{id:"leitor",nome:"Consulta e Relatórios",cargo:"Leitor",codigo:"LEITOR26",perfil:"leitor",cor:"#7B3F00",icone:"👁"}];
const PODE={admin:{registar:true,editar:true,eliminar:true,gerir:true},editor:{registar:true,editar:true,eliminar:false,gerir:false},leitor:{registar:false,editar:false,eliminar:false,gerir:false}};
const CLASSES=["Nazaré de Castro","Castro João dos Santos","Revº Diogo de Sousa"];
const ORGANISMOS=["Organização dos Homens","Organização das Mulheres","OJA","Juventude","Ministério com Crianças","Nenhum"];
const STATUS=["Catecúmeno","À Prova","Efectivo","Falecido","Transferido"];
const SEXO=["Masculino","Feminino"];
const GUIAS={"Nazaré de Castro":"Marolina Bule Domingos","Castro João dos Santos":"Eva Francisco Ernesto","Revº Diogo de Sousa":"Florinda André João"};
const DIRECTORES={"Organização dos Homens":"Mateus Zombo","Organização das Mulheres":"Teresa Manuel João","OJA":"Dionísia N. Samuel","Juventude":"Por nomear","Ministério com Crianças":"Rodrigues Luís Dembo"};
const COR={azul:"#1F3864",azulM:"#2E5096",dourado:"#7B3F00",verde:"#1B5E20",verm:"#B71C1C",cinza:"#37474F",cinzaL:"#ECEFF1"};
const CHAVE="cm_benjamim_v1";
const DADOS=[{id:1,nome:"Marolina Bule Domingos",classe:"Nazaré de Castro",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2018-03-10",telefone:"",obs:"Guia de Classe"},{id:2,nome:"Adão Lopes Mainga",classe:"Nazaré de Castro",sexo:"Masculino",status:"Efectivo",organismo:"Organização dos Homens",baptizado:true,dataBaptismo:"2015-06-14",telefone:"",obs:"Vice Guia Leigo"},{id:3,nome:"Teresa Manuel João",classe:"Nazaré de Castro",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2012-11-20",telefone:"",obs:"Directora Org. Mulheres"},{id:4,nome:"Beatriz Gaspar Cavunga",classe:"Nazaré de Castro",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2010-06-05",telefone:"",obs:"Guia Leiga"},{id:5,nome:"Eva Francisco Ernesto",classe:"Castro João dos Santos",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2014-03-15",telefone:"",obs:"Guia de Classe"},{id:6,nome:"Adão António Ernesto",classe:"Castro João dos Santos",sexo:"Masculino",status:"Efectivo",organismo:"Organização dos Homens",baptizado:true,dataBaptismo:"2011-11-27",telefone:"",obs:"Presidente da Junta"},{id:7,nome:"Florinda André João",classe:"Revº Diogo de Sousa",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2009-06-14",telefone:"",obs:"Guia de Classe"},{id:8,nome:"Marquinha Miguel",classe:"Revº Diogo de Sousa",sexo:"Feminino",status:"Efectivo",organismo:"Organização das Mulheres",baptizado:true,dataBaptismo:"2015-03-22",telefone:"",obs:"Evangelismo e Oração"}];
function lerLocal(){try{const r=localStorage.getItem(CHAVE);if(r)return JSON.parse(r);}catch(_){}return null;}
function guardarLocal(m){try{localStorage.setItem(CHAVE,JSON.stringify({membros:m,ts:Date.now()}));}catch(_){}}
function useStorage(){const[membros,setMembros]=React.useState(()=>{const l=lerLocal();return l?l.membros:DADOS;});const[salvando,setSalvando]=React.useState(false);const[guardadoOk,setGuardadoOk]=React.useState(false);const guardar=React.useCallback(async(novos)=>{setSalvando(true);setMembros(novos);guardarLocal(novos);setSalvando(false);setGuardadoOk(true);setTimeout(()=>setGuardadoOk(false),2000);},[]);return{membros,salvando,guardadoOk,guardar};}
function LogoIMU({size=48}){return React.createElement("svg",{viewBox:"0 0 200 230",width:size,height:size},React.createElement("path",{d:"M68 222 C54 194 22 176 20 144 C18 116 38 104 44 82 C49 63 40 46 47 30 C54 14 70 7 79 0 C72 20 76 36 84 50 C90 62 88 73 83 87 C77 105 65 116 67 138 C69 156 83 167 88 185 C93 198 91 212 87 224 Z",fill:"#D32F2F"}),React.createElement("path",{d:"M68 222 C54 194 22 176 20 144 C18 116 38 104 44 82 C49 63 40 46 47 30 C60 44 65 60 60 78 C55 96 42 108 46 130 C49 150 64 161 68 180 C72 195 70 208 68 222 Z",fill:"white",opacity:"0.3"}),React.createElement("rect",{x:"102",y:"12",width:"20",height:"206",rx:"3",fill:"#111"}),React.createElement("rect",{x:"70",y:"70",width:"116",height:"20",rx:"3",fill:"#111"}));}
function Badge({txt}){const m={Efectivo:{bg:"#E8F5E9",c:"#1B5E20"},"Catecúmeno":{bg:"#E3F2FD",c:"#0D47A1"},"À Prova":{bg:"#FFF3E0",c:"#E65100"},Falecido:{bg:"#EFEBE9",c:"#4E342E"},Transferido:{bg:"#F3E5F5",c:"#6A1B9A"}};const s=m[txt]||{bg:"#ECEFF1",c:"#555"};return React.createElement("span",{style:{background:s.bg,color:s.c,border:"1px solid "+s.c+"30",borderRadius:12,padding:"2px 10px",fontSize:11,fontWeight:700,whiteSpace:"nowrap"}},txt);}
function MiniBar({valor,max,color}){return React.createElement("div",{style:{height:5,borderRadius:3,background:"#eee",overflow:"hidden",flex:1}},React.createElement("div",{style:{width:Math.round((valor/Math.max(max,1))*100)+"%",height:"100%",background:color,borderRadius:3}}));}
function StatCard({icon,label,value,sub,color}){return React.createElement("div",{style:{background:"#fff",borderLeft:"4px solid "+color,border:"1px solid "+color+"18",borderRadius:10,padding:"13px 16px",flex:"1 1 100px"}},React.createElement("div",{style:{fontSize:18,marginBottom:2}},icon),React.createElement("div",{style:{fontSize:23,fontWeight:900,color:color,fontFamily:"Georgia,serif",lineHeight:1}},value),React.createElement("div",{style:{fontSize:10,fontWeight:700,color:"#666",marginTop:3,textTransform:"uppercase"}},label),sub&&React.createElement("div",{style:{fontSize:9,color:"#aaa",marginTop:1}},sub));}
const VAZIO={id:null,nome:"",classe:CLASSES[0],sexo:SEXO[0],status:STATUS[0],organismo:ORGANISMOS[5],baptizado:false,dataBaptismo:"",telefone:"",obs:""};
function Modal({membro,salvando,onSave,onClose}){const[form,setForm]=React.useState({...membro});const set=(k,v)=>setForm(f=>({...f,[k]:v}));const ok=form.nome.trim().length>2;const lbl={fontSize:11,fontWeight:700,color:"#666",textTransform:"uppercase",letterSpacing:"0.05em",marginBottom:3,display:"block"};const inp={width:"100%",padding:"8px 10px",border:"1.5px solid #ddd",borderRadius:7,fontSize:13,fontFamily:"inherit",boxSizing:"border-box",outline:"none",background:"#fafafa"};
return React.createElement("div",{style:{position:"fixed",inset:0,background:"rgba(0,0,0,0.62)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",padding:16}},
React.createElement("div",{style:{background:"#fff",borderRadius:14,width:"100%",maxWidth:540,maxHeight:"92vh",overflowY:"auto",boxShadow:"0 24px 64px rgba(0,0,0,0.38)"}},
React.createElement("div",{style:{background:"linear-gradient(135deg,"+COR.azul+","+COR.azulM+")",borderRadius:"14px 14px 0 0",padding:"14px 20px",display:"flex",justifyContent:"space-between",alignItems:"center"}},
React.createElement("div",{style:{display:"flex",alignItems:"center",gap:10}},React.createElement(LogoIMU,{size:28}),
React.createElement("div",null,React.createElement("div",{style:{color:"#fff",fontWeight:800,fontSize:14,fontFamily:"Georgia,serif"}},form.id?"✏️ Editar Membro":"➕ Registar Novo Membro"),
React.createElement("div",{style:{color:"#ffffff77",fontSize:11}},"Centro Missionário Revº. Benjamim Manuel"))),
React.createElement("button",{onClick:onClose,style:{background:"rgba(255,255,255,0.15)",border:"none",color:"#fff",fontSize:15,cursor:"pointer",borderRadius:7,padding:"3px 9px"}},"✕")),
React.createElement("div",{style:{padding:"16px 20px 20px"}},
React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:11}},
React.createElement("div",{style:{gridColumn:"1/-1"}},React.createElement("label",{style:lbl},"Nome Completo *"),
React.createElement("input",{style:Object.assign({},inp,{borderColor:ok?"#ddd":"#ffb3b3"}),value:form.nome,onChange:function(e){set("nome",e.target.value);},placeholder:"Nome completo",autoFocus:true}),
!ok&&form.nome.length>0&&React.createElement("div",{style:{fontSize:10,color:"#c00",marginTop:2}},"Mínimo 3 caracteres")),
React.createElement("div",null,React.createElement("label",{style:lbl},"Classe *"),React.createElement("select",{style:inp,value:form.classe,onChange:function(e){set("classe",e.target.value);}},CLASSES.map(function(c){return React.createElement("option",{key:c},c);}))),
React.createElement("div",null,React.createElement("label",{style:lbl},"Sexo"),React.createElement("select",{style:inp,value:form.sexo,onChange:function(e){set("sexo",e.target.value);}},SEXO.map(function(s){return React.createElement("option",{key:s},s);}))),
React.createElement("div",null,React.createElement("label",{style:lbl},"Estado *"),React.createElement("select",{style:inp,value:form.status,onChange:function(e){set("status",e.target.value);}},STATUS.map(function(s){return React.createElement("option",{key:s},s);}))),
React.createElement("div",null,React.createElement("label",{style:lbl},"Organismo"),React.createElement("select",{style:inp,value:form.organismo,onChange:function(e){set("organismo",e.target.value);}},ORGANISMOS.map(function(o){return React.createElement("option",{key:o},o);}))),
React.createElement("div",null,React.createElement("label",{style:lbl},"Telefone"),React.createElement("input",{style:inp,value:form.telefone,onChange:function(e){set("telefone",e.target.value);},placeholder:"9XXXXXXXX"})),
React.createElement("div",{style:{display:"flex",flexDirection:"column",justifyContent:"center",gap:5}},React.createElement("label",{style:lbl},"Baptizado?"),
React.createElement("div",{style:{display:"flex",alignItems:"center",gap:10}},
React.createElement("input",{type:"checkbox",checked:form.baptizado,onChange:function(e){set("baptizado",e.target.checked);},style:{width:17,height:17,cursor:"pointer"}}),
React.createElement("span",{style:{fontSize:13,color:form.baptizado?COR.verde:"#bbb",fontWeight:700}},form.baptizado?"✓ Sim":"Não"))),
form.baptizado&&React.createElement("div",null,React.createElement("label",{style:lbl},"Data do Baptismo"),React.createElement("input",{type:"date",style:inp,value:form.dataBaptismo,onChange:function(e){set("dataBaptismo",e.target.value);}})),
React.createElement("div",{style:{gridColumn:"1/-1"}},React.createElement("label",{style:lbl},"Observações / Cargo"),React.createElement("input",{style:inp,value:form.obs,onChange:function(e){set("obs",e.target.value);},placeholder:"Ex: Guia de Classe..."}))),
React.createElement("div",{style:{display:"flex",gap:10,marginTop:16,justifyContent:"flex-end"}},
React.createElement("button",{onClick:onClose,style:{padding:"8px 18px",border:"1.5px solid #ddd",borderRadius:8,background:"#fff",cursor:"pointer",fontSize:13,fontWeight:600,color:"#555"}},"Cancelar"),
React.createElement("button",{onClick:function(){if(ok)onSave(form);},disabled:!ok||salvando,style:{padding:"8px 20px",border:"none",borderRadius:8,background:ok&&!salvando?"linear-gradient(135deg,"+COR.azul+","+COR.azulM+")":"#ccc",color:"#fff",cursor:ok&&!salvando?"pointer":"not-allowed",fontSize:13,fontWeight:700}},salvando?"⏳ A guardar…":form.id?"💾 Guardar":"✅ Registar")))));}
function EcraLogin({onLogin}){const[codigo,setCodigo]=React.useState("");const[erro,setErro]=React.useState("");const[mostrar,setMostrar]=React.useState(false);const[tentativas,setTentativas]=React.useState(0);const bloqueado=tentativas>=5;
function tentar(){if(bloqueado)return;const u=UTILIZADORES.find(function(u){return u.codigo===codigo.trim().toUpperCase();});if(u){onLogin(u);}else{const n=tentativas+1;setTentativas(n);setErro(n>=5?"Demasiadas tentativas. Recarrega a página.":"Código incorrecto. "+(5-n)+" tentativa(s) restante(s).");setCodigo("");}}
return React.createElement("div",{style:{minHeight:"100vh",background:"linear-gradient(145deg,"+COR.azul+" 0%,"+COR.azulM+" 50%,#2a5298 100%)",display:"flex",alignItems:"center",justifyContent:"center",padding:16}},
React.createElement("div",{style:{background:"#fff",borderRadius:20,width:"100%",maxWidth:400,boxShadow:"0 32px 80px rgba(0,0,0,0.4)",overflow:"hidden"}},
React.createElement("div",{style:{background:"linear-gradient(135deg,"+COR.azul+","+COR.azulM+")",padding:"28px 28px 22px",textAlign:"center"}},
React.createElement("div",{style:{display:"flex",justifyContent:"center",marginBottom:10}},React.createElement(LogoIMU,{size:62})),
React.createElement("div",{style:{color:"#fff",fontWeight:800,fontSize:17,fontFamily:"Georgia,serif"}},"Base de Dados de Membros"),
React.createElement("div",{style:{color:"#ffffffbb",fontSize:12,marginTop:3}},"Centro Missionário Revº. Benjamim Manuel"),
React.createElement("div",{style:{color:"#ffffff77",fontSize:11,marginTop:1}},"Circuito dos Mulenvos de Baixos")),
React.createElement("div",{style:{padding:"26px 26px 30px"}},
React.createElement("div",{style:{textAlign:"center",marginBottom:20}},
React.createElement("div",{style:{fontSize:15,fontWeight:700,color:COR.azul,fontFamily:"Georgia,serif"}},"🔑 Acesso ao Sistema"),
React.createElement("div",{style:{fontSize:12,color:"#999",marginTop:3}},"Introduz o teu código de acesso")),
React.createElement("div",{style:{display:"flex",gap:8,marginBottom:20}},
UTILIZADORES.map(function(u){return React.createElement("div",{key:u.id,style:{flex:1,background:u.cor+"11",border:"1.5px solid "+u.cor+"33",borderRadius:10,padding:"10px 6px",textAlign:"center"}},
React.createElement("div",{style:{fontSize:18,marginBottom:2}},u.icone),
React.createElement("div",{style:{fontSize:10,fontWeight:700,color:u.cor,textTransform:"uppercase"}},u.cargo),
React.createElement("div",{style:{fontSize:9,color:"#aaa",marginTop:1}},u.perfil==="admin"?"Acesso total":u.perfil==="editor"?"Registar+editar":"Só consultar"));})),
React.createElement("div",{style:{marginBottom:14}},
React.createElement("label",{style:{fontSize:11,fontWeight:700,color:"#666",textTransform:"uppercase",letterSpacing:"0.05em",marginBottom:6,display:"block"}},"Código de Acesso"),
React.createElement("div",{style:{position:"relative"}},
React.createElement("input",{type:mostrar?"text":"password",value:codigo,onChange:function(e){setCodigo(e.target.value.toUpperCase());setErro("");},onKeyDown:function(e){if(e.key==="Enter")tentar();},disabled:bloqueado,placeholder:"Introduz o código",autoFocus:true,style:{width:"100%",padding:"12px 44px 12px 14px",border:"2px solid "+(erro?"#ffaaaa":"#ddd"),borderRadius:10,fontSize:15,fontFamily:"monospace",letterSpacing:"0.2em",fontWeight:700,outline:"none",boxSizing:"border-box"}}),
React.createElement("button",{onClick:function(){setMostrar(function(m){return !m;});},style:{position:"absolute",right:12,top:"50%",transform:"translateY(-50%)",background:"none",border:"none",cursor:"pointer",fontSize:15,color:"#bbb"}},mostrar?"🙈":"👁")),
erro&&React.createElement("div",{style:{fontSize:12,color:bloqueado?"#B71C1C":"#E65100",marginTop:5,fontWeight:600}},"⚠️ ",erro)),
React.createElement("button",{onClick:tentar,disabled:!codigo||bloqueado,style:{width:"100%",padding:"12px",border:"none",borderRadius:10,cursor:codigo&&!bloqueado?"pointer":"not-allowed",background:codigo&&!bloqueado?"linear-gradient(135deg,"+COR.azul+","+COR.azulM+")":"#e0e0e0",color:"#fff",fontSize:15,fontWeight:800,fontFamily:"inherit"}},"Entrar →"),
React.createElement("div",{style:{textAlign:"center",marginTop:14,fontSize:11,color:"#ccc"}},"Códigos fornecidos pelo Administrador"))));}
function GestaoCodigos({onFechar}){return React.createElement("div",{style:{position:"fixed",inset:0,background:"rgba(0,0,0,0.65)",zIndex:2000,display:"flex",alignItems:"center",justifyContent:"center",padding:16}},React.createElement("div",{style:{background:"#fff",borderRadius:16,width:"100%",maxWidth:460,boxShadow:"0 24px 64px rgba(0,0,0,0.4)"}},React.createElement("div",{style:{background:"linear-gradient(135deg,"+COR.azul+","+COR.azulM+")",borderRadius:"16px 16px 0 0",padding:"14px 20px",display:"flex",justifyContent:"space-between",alignItems:"center"}},React.createElement("div",{style:{display:"flex",alignItems:"center",gap:8}},React.createElement(LogoIMU,{size:26}),React.createElement("div",{style:{color:"#fff",fontWeight:800,fontSize:14,fontFamily:"Georgia,serif"}},"🔐 Códigos de Acesso")),React.createElement("button",{onClick:onFechar,style:{background:"rgba(255,255,255,0.15)",border:"none",color:"#fff",fontSize:14,cursor:"pointer",borderRadius:7,padding:"3px 8px"}},"✕")),React.createElement("div",{style:{padding:"18px 20px 22px"}},UTILIZADORES.map(function(u){return React.createElement("div",{key:u.id,style:{background:u.cor+"0A",border:"1.5px solid "+u.cor+"25",borderRadius:10,padding:"12px 14px",marginBottom:10}},React.createElement("div",{style:{display:"flex",alignItems:"center",gap:8,marginBottom:6}},React.createElement("span",{style:{fontSize:18}},u.icone),React.createElement("div",null,React.createElement("div",{style:{fontWeight:800,fontSize:13,color:u.cor}},u.cargo),React.createElement("div",{style:{fontSize:11,color:"#888"}},u.perfil==="admin"?"Acesso total":u.perfil==="editor"?"Registar + editar (sem eliminar)":"Só consultar e relatórios"))),React.createElement("div",{style:{display:"flex",alignItems:"center",gap:10,background:"#fff",border:"1.5px solid #eee",borderRadius:8,padding:"8px 12px"}},React.createElement("span",{style:{fontSize:11,fontWeight:700,color:"#888",textTransform:"uppercase",whiteSpace:"nowrap"}},"Código:"),React.createElement("span",{style:{fontFamily:"monospace",fontWeight:800,fontSize:16,letterSpacing:"0.2em",color:u.cor,flex:1}},u.codigo),React.createElement("button",{onClick:function(){if(navigator.clipboard)navigator.clipboard.writeText(u.codigo);},style:{background:u.cor+"15",border:"none",color:u.cor,fontSize:11,cursor:"pointer",borderRadius:6,padding:"4px 8px",fontWeight:700}},"Copiar")));}),React.createElement("div",{style:{background:"#E8F5E9",border:"1px solid #A5D6A7",borderRadius:8,padding:"10px 14px",marginTop:14,fontSize:12,color:COR.verde}},"💡 Envia cada código à respectiva pessoa por WhatsApp ou SMS."),React.createElement("div",{style:{display:"flex",justifyContent:"flex-end",marginTop:14}},React.createElement("button",{onClick:onFechar,style:{padding:"9px 22px",background:"linear-gradient(135deg,"+COR.azul+","+COR.azulM+")",color:"#fff",border:"none",borderRadius:8,cursor:"pointer",fontSize:13,fontWeight:700}},"Fechar")))));}
function App(){const{membros,salvando,guardadoOk,guardar}=useStorage();const[utilizador,setUtilizador]=React.useState(null);const[modal,setModal]=React.useState(null);const[tab,setTab]=React.useState("lista");const[busca,setBusca]=React.useState("");const[fClasse,setFClasse]=React.useState("Todas");const[fStatus,setFStatus]=React.useState("Todos");const[fOrg,setFOrg]=React.useState("Todos");const[confirmarDel,setConfirmarDel]=React.useState(null);const[toast,setToast]=React.useState(null);const[gerir,setGerir]=React.useState(false);
function mostrarToast(msg,tipo){setToast({msg:msg,tipo:tipo||"ok"});setTimeout(function(){setToast(null);},3000);}
const pode=utilizador?PODE[utilizador.perfil]:PODE.leitor;
const filtrados=React.useMemo(function(){return membros.filter(function(m){const b=busca.toLowerCase();if(b&&!m.nome.toLowerCase().includes(b)&&!m.telefone.includes(b)&&!m.obs.toLowerCase().includes(b))return false;if(fClasse!=="Todas"&&m.classe!==fClasse)return false;if(fStatus!=="Todos"&&m.status!==fStatus)return false;if(fOrg!=="Todos"&&m.organismo!==fOrg)return false;return true;});},[membros,busca,fClasse,fStatus,fOrg]);
const stats=React.useMemo(function(){const act=membros.filter(function(m){return!["Falecido","Transferido"].includes(m.status);});return{total:act.length,masc:act.filter(function(m){return m.sexo==="Masculino";}).length,fem:act.filter(function(m){return m.sexo==="Feminino";}).length,catec:act.filter(function(m){return m.status==="Catecúmeno";}).length,prova: